# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
