# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20200421_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tafasel',
            field=models.TextField(default=''),
        ),
    ]
