# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_post_tafasel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images/'),
        ),
    ]
