# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200505_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageone',
            field=models.ImageField(default='post_img/default.png', upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagethree',
            field=models.ImageField(default='post_img/default.png', upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagetwo',
            field=models.ImageField(default='post_img/default.png', upload_to='post_img/'),
        ),
    ]
