# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20200505_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagethree',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagetwo',
        ),
    ]
