# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200420_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='General User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, default='USER IN DAHABSHOP', max_length=50),
        ),
    ]
